/**
 * Vercel Cron Job: triggers an automated backup if the configured schedule
 * matches the current day-of-week.
 *
 * Wired up via vercel.json:
 *   { "crons": [{ "path": "/api/cron/backup", "schedule": "0 1 * * *" }] }
 *
 * On Vercel's Hobby plan, cron jobs run at most once per 24h, so we run
 * once daily and only consult the user's schedule for *which* weekdays to
 * back up on. The "hour" / "minute" fields in the schedule become
 * informational on serverless (the actual run time is the cron expression).
 *
 * Vercel signs cron requests with `Authorization: Bearer $CRON_SECRET`
 * (CRON_SECRET is auto-generated by Vercel and exposed to the function).
 */

import { NextRequest, NextResponse } from "next/server";
import { readSchedule } from "@/lib/backup/config";
import { writeBackupFile } from "@/lib/backup/writer";
import { autoCommentFor } from "@/lib/backup/scheduler";
import { logAudit, A } from "@/lib/security/audit";

export const runtime = "nodejs";
export const maxDuration = 60; // seconds — covers a few-MB JSON backup on Hobby

export async function GET(req: NextRequest) {
  // Vercel sets CRON_SECRET automatically when cron jobs are configured.
  // Locally, the route can be hit without auth (for testing) — still ok
  // because no destructive action happens unless the schedule matches.
  const cronSecret = process.env.CRON_SECRET;
  if (cronSecret) {
    const authHeader = req.headers.get("authorization");
    if (authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }
  }

  const schedule = await readSchedule();
  const now = new Date();
  const today = now.getDay(); // 0 = Sunday, 6 = Saturday
  const days = schedule.daysOfWeek;
  // Empty array == "every day" (matches the UI label)
  const dayMatches = days.length === 0 || days.includes(today);

  if (!schedule.enabled) {
    return NextResponse.json({
      ok: true,
      ranBackup: false,
      reason: "schedule disabled",
      now: now.toISOString(),
    });
  }
  if (!dayMatches) {
    return NextResponse.json({
      ok: true,
      ranBackup: false,
      reason: `today (${today}) not in scheduled days [${days.join(",")}]`,
      now: now.toISOString(),
    });
  }

  try {
    const filename = await writeBackupFile(autoCommentFor(schedule));
    await logAudit({
      action: A.BACKUP_CREATED,
      detail: `cron-auto: ${filename}`,
    });
    return NextResponse.json({
      ok: true,
      ranBackup: true,
      filename,
      now: now.toISOString(),
    });
  } catch (e) {
    console.error("[cron:backup] failed", e);
    return NextResponse.json(
      { ok: false, error: String(e), now: now.toISOString() },
      { status: 500 }
    );
  }
}
